version: "3.9"

services:
  service-agent:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"

    environment:
      MONGO_URI: 
      DEBUG_MODE: 1
      DOCKER_DEAMON_BASE_URI: unix://var/run/docker.sock
      
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock